services:
  - type: web
    name: mise
    runtime: python
    plan: free
    envVars:
      - key: CALLE_API_KEY
        sync: false
      - key: CALLE_BASE_URL
        sync: false
      - key: CALLE_PHONE
        sync: false
    buildCommand: ""
    startCommand: python3 server.py --db contractor.db
